# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Devansh's Link Tree"

# Avatar image path
avatar: "./images/profile.jpg"

# Name section text
name: "Devansh Vashishat (@bugslayer01)"

# Tagline section text
tagline: >-
    Backend & DevOps engineer with a growing fascination for algorithms and competitive programming

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-regular fa-file"
      text: "Resume <span class='link-button-text'>(100+ Posts)</span>"
      url: "https://resume.dev-ansh.xyz"
      alt: "Devansh's Resume"
      title: "Devansh's Resume"
      target: "_blank"
  - link:
      icon: "fa-solid fa-code"
      text: "Leetcode"
      url: "https://leetcode.com/u/iCodeInCpp/"
      alt: "Devansh on Leetcode"
      title: "Leetcode Profile"
      target: "_blank"
  - link:
      icon: "fa-solid fa-code"
      text: "Codeforces"
      url: "https://codeforces.com/profile/devansh28112004"
      alt: "Devansh on Codeforces"
      title: "Codeforces Profile"
      target: "_blank"
  - link:
      icon: "fa-solid fa-terminal"
      text: "AtCoder"
      url: "https://atcoder.jp/users/bugslayer01"
      alt: "Devansh on AtCoder"
      title: "AtCoder Profile"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/bugslayer01"
      title: "Devansh's GitHub"
      alt: "Devansh's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://x.com/bugslayer01"
      title: "Devansh's Twitter"
      alt: "Devansh's Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/bugslayer01/"
      title: "Devansh's LinkedIn"
      alt: "Devansh's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:devanshvashishat@gmail.com"
      title: "Email: devanshvashishat@gmail.com"
      alt: "devanshvashishat@gmail.com"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on  GitHub, or stay connected on  LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  Devansh Vashishat. All rights reserved.